defaults:
  - setup

# Dataset params:
name: ABCD
skills: ['turn_on_lightbulb', 'move_slider_left', 'turn_on_led', 'open_drawer'] # ['open_drawer', 'turn_on_lightbulb', 'move_slider_left', 'turn_on_led']

# GMM params
n_components: 3
max_steps: 0
skill_max_steps: 128