defaults:
  - setup

# Dataset params:
name: ABCD
skills: ['open_drawer', 'turn_on_lightbulb', 'turn_on_led'] # ['open_drawer', 'turn_on_lightbulb', 'move_slider_left', 'turn_on_led']
state_type: 'pos'

# GMM params
n_components: 3
max_steps: 0
skill_max_steps: 64