#misc
# device: ${device}
discount: 0.99

#rl dataset
batch_size: 256

#actor
actor_lr: 3e-4
actor_betas: [0.9, 0.999]

#critic
critic_lr: 3e-4
critic_tau: 0.005
critic_betas: [0.9, 0.999]

#alpha
optimize_alpha: true
alpha_lr: 3e-4
init_alpha: 0.2
alpha_betas: [0.9, 0.999]

# #ae
# ae_lr: 3e-4
# shared_encoder: true
# fixed_encoder: false

# evaluation frequency:
eval_frequency: 50
