seed: 0
use_vr: false
bullet_time_step: 240.0
show_gui: false
use_scene_info: true
use_egl: false

defaults:
  - cameras@cameras: static_and_gripper
  - scene@scene_cfg: calvin_scene_D
  - robot@robot_cfg: panda_longer_finger
  - tasks@tasks: customized_tasks
