defaults:
  - extractmodule: default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
slurm: false

root: /home/lagandua/projects/refining-skill-sequences

log_dir: ${root}/examples/CALVINExperiment/logs
# output directory where demos will be saved
demos_dir: ${root}/examples/CALVINExperiment/data/demos

skills_to_extract: ${root}/examples/CALVINExperiment/demos_extract/skills_to_extract.txt
skill: null

hydra:
  run:
    dir: ${log_dir}/extract-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/extract-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.dataset.data_dir
          - datamodule.dataset.num_workers