defaults:
  - calvin_env: default
  - setup
  - skills_setup

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


# Task params
target_tasks: ['open_drawer', 'close_drawer']
task_sequential: true
sparse_rewards: true # true (reward only for successful full task) or false (reward for successful sub tasks also)

# Task Demos
demos_dir: ${root}/examples/CALVINExperiment/data/demos

# Task params
task: ${target_tasks} 

# Environment params
render: false
record: false

# WANDB Logging Params
wandb: false

hydra:
  run:
    dir: ${log_dir}/eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir