defaults:
  - calvin_env: full_default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ${root}/examples/CALVINExperiment/logs
slurm: false

root: /home/lagandua/projects/refining-skill-sequences

# Skill Demos
demos_dir: /work/dlclarge1/lagandua-refine-skills/calvin_demos/

# Skill params
skills_dir: ${root}/examples/CALVINExperiment/skills_ds
skills_list: ${skills_dir}/skillnames_one.txt
state_type: 'pos_ori'

# Evaluation params
max_steps: 1000
# sampling_dt: 1/30


# Environment params
render: false
record: true

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/eval_ds
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/eval_ds
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir