defaults:
  - calvin_env: default_close
  - dataset: calvin_ds 
  - dyn_sys: clfds # clfds or manifold_gmm
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ${root}/examples/CALVINExperiment/logs
slurm: false

root: /home/lagandua/projects/refining-skill-sequences

# Skill Demos
demos_dir: /work/dlclarge1/lagandua-refine-skills/calvin_demos/

# Skill params
skills_dir: ${root}/examples/CALVINExperiment/skills_ds
skills_list: ${skills_dir}/skillnames_close.txt
state_type: 'pos'
dim: none

# Dataset params:
skill: none
train: false # false to load validation dataset
goal_centered: false
dt: 0.0666
sampling_dt: 0.0333
is_quaternion: false

# Evaluation and DS params
max_steps: 240
# ds_type: 'clfds' 
# ds_type: 'gmm'

# GMM params
gmm_components: 7
plot_with_mlab: false

# Environment params
render: false
record: false

# WANDB Logging Params
wandb: false

temp: false

hydra:
  run:
    dir: ${log_dir}/eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir