defaults:
  - calvin_env: default # or default_close for close_drawer
  - setup
  - skills_setup

# Environment params
render: false
record: false

# WANDB Logging Params
wandb: false

goal_centered: false


hydra:
  run:
    dir: ${log_dir}/ds-eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/ds-eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir