defaults:
  - calvin_env: config_data_collection
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ${root}/examples/CALVINExperiment/logs
slurm: false

root: /home/lagandua/projects/refining-skill-sequences

# Skill Demos
demos_dir: /work/dlclarge1/lagandua-refine-skills/calvin_demos/

# Skill params
skills_dir: ${root}/examples/CALVINExperiment/skills_ds
skills_list: ${skills_dir}/skillnames_one.txt
state_type: 'joint'

# Evaluation params
max_steps: 1000
sampling_dt: 0.06666


# Environment params
render: false
record: false

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d-%H-%M-%S}/
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d-%H-%M-%S}/
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir