defaults:
  - calvin_env: default
  - rl: sac
  - rl/agent: seqblend_rl
  - setup
  - skills_setup
  - wandb

# Experiment things
exp_dir: null
target_tasks: ['open_drawer', 'close_drawer']
task_sequential: true # Does order of the skill matter?


# Training Hyperparameters
random_seeds: 1
num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 5000
eval_frequency: 50 # episodes
num_eval_episodes: 5
accumulate_env_steps: 16
max_episode_steps: 10

# Visualization
render: false
record: true



hydra:
  run:
    dir: ${log_dir}/seqblendrl-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/seqblendrl-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir