defaults:
  - calvin_env: default
  - rl: sac
  - rl/agent: seqblend_rl_toy
  - setup
  - skills_setup
  - wandb

# Experiment things
exp_dir: null
target_tasks: ['open_drawer', 'close_drawer']
task_sequential: true # Does order of the skills matter?


# Training Hyperparameters
random_seeds: 1
num_train_steps: 1e5
replay_buffer_capacity: 1e5
num_seed_steps: 256
eval_frequency: 250 # episodes
num_eval_episodes: 5
accumulate_env_steps: 64
max_episode_steps: 2

# Visualization
render: false
record: true



hydra:
  run:
    dir: ${log_dir}/seqblendrl-train/${now:%m%d}/${now:%H%M%S}
  sweep:
    dir: ${log_dir}/seqblendrl-train/${now:%m%d}/${now:%H%M%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir