defaults:
  - _self_
  - setup
  - skills_setup


  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# WANDB Logging params
wandb: true

hydra:
  run:
    dir: ${log_dir}/ds-train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/ds-train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir