defaults:
  - dyn_sys: manifold_gmm # clfds or manifold_gmm
  - dataset: calvin_ds
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ${root}/examples/CALVINExperiment/logs
slurm: false

root: /home/lagandua/projects/refining-skill-sequences

# Skill Demos
demos_dir: /work/dlclarge1/lagandua-refine-skills/calvin_demos/

# Skill params
skills_dir: ${root}/examples/CALVINExperiment/skills_ds
skills_list: ${skills_dir}/skillnames_one.txt
state_type: 'pos'
dim: none

# Dataset params:
skill: none
train: true # false to load validation dataset
goal_centered: true
dt: 0.0666
sampling_dt: 0.0333
is_quaternion: false

# DS params
# ds_type: 'clfds'
ds_type: 'gmm'

# GMM params
gmm_components: 3
plot_with_mlab: false

# Training params
lr: 1e-3
max_epochs: 3000
batch_size: 100

# WANDB Logging Params
wandb: false

hydra:
  run:
    dir: ${log_dir}/train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir