defaults:
  - clfds: default
  - gmm: default
  - dataset: calvin_ds
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ${root}/examples/CALVINExperiment/logs
slurm: false

root: /home/lagandua/projects/refining-skill-sequences

# WANDB Logging Params
wandb: true

# Skill Demos
demos_dir: /work/dlclarge1/lagandua-refine-skills/calvin_demos/

# Skill params
skills_dir: ${root}/examples/CALVINExperiment/skills_ds
skills_list: ${skills_dir}/skillnames_close.txt
state_type: 'joint'
dim: none

# Dataset params:
skill: none
train: true # false to load validation dataset
goal_centered: true
dt: 0.0666
sampling_dt: 0.0666

# DS params
ds_type: 'clfds' # or 'gmm'

# Training params
lr: 1e-3
max_epochs: 3000
batch_size: 100


hydra:
  run:
    dir: ${log_dir}/train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir