default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.8
        exclude: examples/CALVINExperiment/calvin_env/
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: examples/(MovementPrimitives|GripperExperiment)/