_target_: sac_gmm.networks.autoencoder.AutoEncoder
_recursive_: false
hd_input_space: ??
in_channels: ??
hidden_dim: ${rl.compact_rep_size}
late_fusion: ${rl.late_fusion}
latent_lambda: 0
device: ${device}