_target_: sac_gmm.agent.calvin_sacgmm_agent.CALVINSACGMMAgent
_recursive_: false
calvin_env: ${calvin_env}
dataset: ${dataset}
dyn_sys: ${dyn_sys}
skill: ${skill}
adapt_cov: ${adapt_cov}
mean_shift: ${mean_shift}
state_type: ${state_type}
env_obs_allowed: ${env_obs_allowed}
num_train_steps: ${num_train_steps}
num_seed_steps: ${num_seed_steps}
eval_frequency: ${eval_frequency}
num_eval_episodes: ${num_eval_episodes}
device: ${device}
gmm_window_size: ${gmm_window_size}

render: ${render}
record: ${record}
max_episode_steps: ${max_episode_steps}

wandb: ${wandb}
exp_dir: ${exp_dir}
skills_dir: ${skills_dir}
demos_dir: ${demos_dir}