deterministic: true
accelerator: gpu
devices: 1 #auto
strategy: auto #"ddp", "ddp_spawn", "deepspeed"
precision: 32
max_epochs: 100000
max_steps: -1 # 8e4 will get you just over 8.5K episodes
log_every_n_steps:       1             #help='print/disp/save frequency'
resume_from_checkpoint:  null            #help='path to latest checkpoint'
val_check_interval:      1.0             #help=How often to check the validation set.
limit_val_batches:       1.0
accumulate_grad_batches: 1               #help='number of accumulated batches'