defaults:
  - dataset: calvin
  - transforms: calvin

_target_: sac_gmm.datasets.sac_gmm_datamodule.SACGMMDataModule
_recursive_: false
batch_size:   32
num_workers:  8
step_len:     1
skill: open_drawer