defaults:
  - default
  - encoder: default
  - actor: default
  - critic: default
  - model: dreamer
  - replay_buffer: replay_buffer_task

model_ckpt: ${model_ckpt}
rb_dir: ${rb_dir}

_target_: sac_n_gmm.rl.sac_n_gmm_ft.SACNGMM_FT
_recursive_: false