defaults:
  - default
  - encoder: default
  - actor: default
  - critic: default
  - model: tdmpc_custom
  - replay_buffer: replay_buffer_task

model_ckpt: ${model_ckpt}
rb_dir: ${rb_dir}

_target_: sac_gmm.rl.sac_n_gmm_mb_ft.SACNGMM_MB_FT
_recursive_: false

