_target_: SkillsSequencing.skills.mps.dynsys.CALVIN_DS.CALVINDynSysDataset
skill: ${skill}
train: ${train}
state_type: ${state_type}
demos_dir: ${demos_dir}
goal_centered: ${goal_centered}
dt: ${dt}
sampling_dt: ${sampling_dt}
