_target_: SkillsRefining.skills.mps.dynsys.CALVIN_DS.CALVINDynSysDataset
skill: ${skill}
train: ${train}
state_type: ${state_type}
demos_dir: ${demos_dir}
goal_centered: ${goal_centered}
dt: ${dt}
sampling_dt: ${sampling_dt}
normalized: ${normalized}
is_quaternion: ${is_quaternion}
ignore_bad_demos: ${ignore_bad_demos}
