defaults:
  - datamodule: default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
slurm: false

root: ~/sac_gmm

log_dir: ${root}/logs
demos_dir: ${root}/demonstrations
skill: null


hydra:
  run:
    dir: ${log_dir}/extract-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/extract-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.dataset.data_dir
          - datamodule.dataset.num_workers