defaults:
  - datamodule: default
  - calvin_env/conf: config_data_collection
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ../
slurm: false

# Skill extraction params
demos_dir: ../demonstrations
use_existing_demos: false
skill: 'turn_off_lightbulb'

# GMM params
gmm_type: base
gmm_components: 3


# Environment params
# cameras: static_and_gripper
# use_egl: false
# use_vr: false
# show_gui: false
# use_scene_info: True

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/gmm
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/gmm
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.dataset.data_dir
          - datamodule.dataset.num_workers