defaults:
  - datamodule: default
  - calvin_env: full_default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
log_dir: ${root}
slurm: false

root: ~/sac_gmm

# Skill extraction params
demos_dir: ${root}/demonstrations
use_existing_demos: true
skill: 'turn_off_lightbulb'

# GMM params
gmm_type: base
gmm_components: 3
plot_gmr: true

# Environment params
render: false

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/gmm
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/gmm
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.dataset.data_dir
          - datamodule.dataset.num_workers