defaults:
  - setup
  - skills_setup
  - calvin_env: open_drawer

# Dataset params:
train: false # false to load validation dataset
goal_centered: false # this must be false during evaluation

# Environment params
render: false
record: false

# Logger
wandb: true

hydra:
  run:
    dir: ${log_dir}/eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir