defaults:
  - setup
  - skill_setup
  - datamodule: calvin_ds5
  - logger: wandb

logger:
  group: gmm-train

show_gui: false


# GMM Type
gmm_type: 5

skill_name: null
skill:
  name: ${skill_name}

# Dataset params:
train: true # false to load validation dataset
goal_centered: true # this must be false during evaluation

# Environment params
render: false
record: false

hydra:
  run:
    dir: ${log_dir}/gmm-train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/gmm-train-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir