defaults:
  - setup
  - setup_task
  - callbacks: default
  - datamodule: calvin_ds2
  - rl: sac_gmm
  - agent: n_sac_gmm_calvin
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

show_gui: false

gmm_type: 2

# evaluation frequency:
eval_frequency: 50
num_init_steps: 256
num_eval_episodes: 50

# Dataset params:
train: true # false to load validation dataset
goal_centered: false # this must be false during evaluation

# Visualization
render: false
record: true

task_order: "ABCD"

model_ckpts: [
  "logs/sacgmm-train/2023_11_19/23_03_43/model_weights/last.ckpt",
  "logs/sacgmm-train/2023_11_19/23_07_06/model_weights/last.ckpt",
  "logs/sacgmm-train/2023_11_19/23_16_05/model_weights/last.ckpt",
  "logs/sacgmm-train/2023_11_19/23_16_21/model_weights/last.ckpt"
  ]

hydra:
  run:
    dir: ${log_dir}/n-sacgmm-eval/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/n-sacgmm-eval/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir