defaults:
  - setup
  - setup_task
  - callbacks: default
  - datamodule: calvin_ds3
  - rl: sac_gmm
  - agent: n_sac_gmm_calvin
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

show_gui: false

gmm_type: 3
skill:
  max_steps: 128
  n_components: 4

sparse_reward: false

# evaluation frequency:
eval_frequency: 50
num_init_steps: 256
num_eval_episodes: 50

# Dataset params:
train: true # false to load validation dataset
goal_centered: false # this must be false during evaluation

# Visualization
render: false
record: true

task_order: "ABCD"

# model_ckpts: [
#   "logs/sacgmm-train/2024_01_11/11_08_30/model_weights/last.ckpt",
#   "logs/sacgmm-train/2024_01_11/11_18_18/model_weights/last.ckpt",
#   "logs/sacgmm-train/2024_01_11/11_19_09/model_weights/last.ckpt",
#   "logs/sacgmm-train/2024_01_11/11_19_30/model_weights/last.ckpt"
#   ]

model_ckpts: [
  "logs/sacgmm-train/2024_01_12/10_54_48/model_weights/last.ckpt",
  "logs/sacgmm-train/2024_01_12/10_55_01/model_weights/last.ckpt",
  "logs/sacgmm-train/2024_01_12/10_55_11/model_weights/last.ckpt",
  "logs/sacgmm-train/2024_01_12/10_55_27/model_weights/episode_number=200.0_total-env-steps=21842.0_accuracy=1.0.ckpt"
  ]

hydra:
  run:
    dir: ${log_dir}/n-sacgmm-eval/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/n-sacgmm-eval/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir