defaults:
  - gmm: manifold_gmm # manifold_gmm or bayesian_gmm
  - skill: ABCD # open_drawer / close_drawer /  
  - env: default_rand_skill # open_drawer / close_drawer / ?

  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

skill:
  state_type: 'pos_ori'
  max_steps: 128