defaults:
  - setup
  - setup_task
  - callbacks: default
  - datamodule: calvin_ds2
  - rl: sac_n_gmm_ft
  - agent: sac_n_gmm_ft_calvin
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# Env params
show_gui: false

# GMM params
gmm_type: 2
skill:
  n_components: 3 # components change for RiepybdlibGMM

task_order: "ABCD"

agent: 
  sparse_reward: false

# Experiment length
max_env_steps: 1e6

# evaluation frequency:
eval_frequency: 25
num_init_steps: 32
num_eval_episodes: 10

# Dataset params:
train: true # false to load validation dataset
goal_centered: true # this must be false during evaluation

# Visualization
render: false
record: true

# Pretrained SAC_N_GMM model
# model_ckpt: "logs/sac-n-gmm-train/2023_10_20/16_17_47/model_weights/last.ckpt"
# rb_dir: "logs/sac-n-gmm-train/2023_10_20/16_17_47/replay_buffer/"

# model_ckpt: "logs/sac-n-gmm-train/2023_11_03/16_40_49/model_weights/last.ckpt"
# rb_dir: "logs/sac-n-gmm-train/2023_11_03/16_40_49/replay_buffer/"

# model_ckpt: "logs/sac-n-gmm-train/2023_11_16/18_24_08/model_weights/last.ckpt"
model_ckpt: "logs/sac-n-gmm-train/2023_11_16/21_00_24/model_weights/episode_number=0_total-env-steps=600531.0_episode_avg_return=0-v1.ckpt"
rb_dir: null # "logs/sac-n-gmm-train/2023_11_13/14_47_07/replay_buffer/"

# Logging
logger:
  group: sac_n_gmm_ft

hydra:
  run:
    dir: ${log_dir}/sac-n-gmm-ft/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/sac-n-gmm-ft/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir