defaults:
  - setup
  - incr_skill_setup
  - callbacks: default
  - datamodule: calvin_ds2
  - sac: sac_n_gmm_ft_model
  - agent: sac_n_gmm_ft_calvin
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# Env params
show_gui: false

# GMM params
gmm_type: 2
skill:
  n_components: 3 # components change for RiepybdlibGMM

task_order: "ABCD"

agent: 
  sparse_reward: false

# evaluation frequency:
eval_frequency: 25
num_init_steps: 256
num_eval_episodes: 10

# Dataset params:
train: true # false to load validation dataset
goal_centered: true # this must be false during evaluation

# Visualization
render: false
record: true

# Pretrained SAC_N_GMM model
# model_ckpt: "logs/sac-n-gmm-train/2023_10_20/16_17_47/model_weights/last.ckpt"
# rb_dir: "logs/sac-n-gmm-train/2023_10_20/16_17_47/replay_buffer/"

# model_ckpt: "logs/sac-n-gmm-train/2023_11_03/16_40_49/model_weights/last.ckpt"
# rb_dir: "logs/sac-n-gmm-train/2023_11_03/16_40_49/replay_buffer/"

model_ckpt: "logs/sac-n-gmm-train/2023_11_06/18_23_55/model_weights/last.ckpt"
rb_dir: null

# Logging
logger:
  group: sac_n_gmm_ft

hydra:
  run:
    dir: ${log_dir}/sac-n-gmm-ft/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/sac-n-gmm-ft/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir