defaults:
  - agent: sacgmm
  - calvin_env: default
  - setup
  - skills_setup
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# skill params
skill: 'open_drawer'

# env params
obs_allowed: ["pos", "rgb_static"] # Order is important = [robot_obs, camera_obs]

# sacgmm
adapt_cov: false

# train and eval
num_train_steps: 5e4
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 1000
eval_frequency: 10
num_eval_episodes: 10
gmm_window_size: 32
gmm_max_episode_steps: 200

# gpu
device: cuda

# logger
log_frequency: 10000
log_save_tb: false

# video recorder (only for evaluation)
record: true

#weight and biases
wandb: true


name: sac_gmm

seed: 1

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M}/${name}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M}/${name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.dataset.data_dir
          - datamodule.dataset.num_workers