defaults:
  - calvin_env: full_default
  - agent: sac_gmm
  - dyn_sys: base_gmm
  - datamodule: default
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# skill params
use_existing_demos: true
skill: 'turn_off_lightbulb'
skill_length: 64

# train and eval
num_train_steps: 5e4
replay_buffer_capacity: 1e2
num_seed_steps: 4
eval_frequency: 10
num_eval_episodes: 100
gmm_window_size: 32
gmm_max_episode_steps: 200

# gpu
device: cuda

# logger
log_frequency: 10000
log_save_tb: false

# video recorder
save_video: true

# directories
root: ~/sac_gmm
log_dir: ${root}
demos_dir: ${root}/demonstrations

name: sac_gmm

seed: 1

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M}/${name}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M}/${name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.dataset.data_dir
          - datamodule.dataset.num_workers