defaults:
  - calvin_env: default # env
  - rl: sac # algorithm
  - rl/agent: calvin_sacgmm_agent # agent that acts in the env
  - setup
  - skills_setup
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Experiment things
exp_dir: null
skill: 'open_drawer'
adapt_cov: False
mean_shift: False

# Environment params
state_type: "pos"
env_obs_allowed: ["pos", "rgb_static"] # Order is important = [robot_obs, camera_obs]

# Training Hyperparameters
random_seeds: 1
num_train_steps: 3e5
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 2
eval_frequency: 50
num_eval_episodes: 5
gmm_window_size: 16
max_episode_steps: 8

# Visualization
render: false
record: false



hydra:
  run:
    dir: ${log_dir}/sac-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/sac-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir