defaults:
  - dataset: calvin_ds
  - model/gmm: bayesian_gmm #manifold_gmm or bayesian_gmm
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
slurm: false
device: cuda

root: /home/${developer}/sac_gmm
log_dir: ${root}/logs
demos_dir: ${root}/demonstrations
exp_dir: null

developer: "nematoli"
comment: ""
