defaults:
  - dataset: calvin_ds
  - dyn_sys: manifold_gmm # clfds or manifold_gmm
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
slurm: false

root: ~/sac_gmm
log_dir: ${root}/logs
demos_dir: ${root}/demonstrations