defaults:
  - gmm: bayesian_gmm # manifold_gmm or bayesian_gmm
  - skill: open_drawer # open_drawer / close_drawer /  
  - env: new_default # open_drawer / close_drawer / ?

  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

