defaults:
  - gmm: manifold_gmm # manifold_gmm or bayesian_gmm
  - task: ABCD # open_drawer / close_drawer /  
  - env: default_task # open_drawer / close_drawer / ?

  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

