_target_: sac_gmm.rl.agent.calvin.n_sac_gmm_calvin.CALVIN_NSACGMMAgent
_recursive_: false

calvin_env: ${env}
datamodule: ${datamodule}

num_init_steps: ${num_init_steps}
num_eval_episodes: ${num_eval_episodes}

priors_change_range: 0.0
mu_change_range: 0.05
quat_change_range: 0.05

task: ${skill}
gmm: ${gmm}
adapt_cov: false
mean_shift: false
adapt_per_skill: 4

exp_dir: ${exp_dir}
root_dir: ${root}
render: ${render}
record: ${record}

rl: ${rl}
model_ckpts: ${model_ckpts}
device: ${device}
sparse_reward: false