_target_: sac_gmm.models.agent.calvin.sac_calvin.CALVINSACAgent
_recursive_: false

calvin_env: ${env}
datamodule: ${datamodule}

num_init_steps: ${num_init_steps}
num_eval_episodes: ${num_eval_episodes}

skill: ${skill}

exp_dir: ${exp_dir}
render: ${render}
record: ${record}