_target_: sac_gmm.rl.agent.calvin.sac_gmm_calvin.CALVINSACGMMAgent
_recursive_: false

calvin_env: ${env}
datamodule: ${datamodule}

num_init_steps: ${num_init_steps}
num_eval_episodes: ${num_eval_episodes}

priors_change_range: 0.0
mu_change_range: 0.05
quat_change_range: 0.05

skill: ${skill}
gmm: ${gmm}
adapt_cov: false
mean_shift: false
adapt_per_episode: 8

exp_dir: ${exp_dir}
render: ${render}
record: ${record}