_target_: pytorch_lightning.callbacks.ModelCheckpoint
_recursive_: false
dirpath: ??
filename: '{episode-number}-{episode-avg-return}'
monitor: 'episode-avg-return' 
verbose: True
save_last: True
save_top_k: 20
mode: 'max'