_target_: pytorch_lightning.callbacks.ModelCheckpoint
_recursive_: false
dirpath: ??
filename: "{episode_number}_{total-env-steps}_{episode_avg_return}"
monitor: 'episode-avg-return' 
verbose: True
save_last: True
save_top_k: 10
mode: 'max'