_target_: pytorch_lightning.callbacks.ModelCheckpoint
save_last: True
save_top_k: 10
monitor: 'eval_episode_return' 
mode: 'max'
verbose: True
dirpath: ${model_dir}
filename: '%s_{step:06d}_{val_episode_return:.3f}''